name: CI
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron:  '0 4 * * 6'  # Run every Sunday

env:
  BUILD_TYPE: Release
  CORES: 2

jobs:
  test:
    name: Unit tests - ${{ matrix.os }} - ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {cc: clang, cxx: clang++, os: ubuntu-latest}
          - {cc: gcc,   cxx: g++,     os: ubuntu-latest}
          - {cc: clang, cxx: clang++, os: macOS-latest}
          - {cc: gcc,   cxx: g++,     os: macOS-latest}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies on Linux
        run: sudo apt-get install ninja-build
        if: contains( matrix.os, 'ubuntu')
      - name: Install dependencies on macOS
        run: brew install ninja
        if: contains( matrix.os, 'macos')
      - name: Build and test
        run: ci/build.sh
        shell: bash
        env:
          CXX: ${{ matrix.cxx }}
          CC:  ${{ matrix.cc  }}
  #
  # Check code style
  #
  style:
    name: Code style
    runs-on: ubuntu-latest
    env:
      CC:  gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install clang-tidy-10
          mkdir ~/bin
          echo -e "#!/bin/sh\nclang-tidy-10 \$@" > ~/bin/clang-tidy
          chmod 755 ~/bin/clang-tidy
      - name: Check code style
        run: ci/build.sh
        env:
          JOB: code_style
  #
  # Sanitise
  #
  sanitise:
    name: Sanitisation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies on Linux
        run: sudo apt-get install ninja-build
      - name: Sanitise address
        run: ci/build.sh
        env:
          SANITISE: address
